### PR TITLE
Add Rails 4 support, validations and I18n support

### PR DESCRIPTION
**Pull request by liquid**
Hello!

I happen to be working on a new Rails app and needed a few things in PublishingLogic. The codebase on master seems to be fairly outdated in many regards and I thought I'll take the time to modernise the gem codebase.

I hope the commits are fairly self-explanatory but here are the main points what this PR introduces:

* Regenerates the gem strcture using modern skeleton by Bundler
* Uses a modern ActiveRecord interface and promotes AR as an explicit dependency (from a dev dependency)
* Removes Gemfile.lock and utilises the gem specification instead
* Adds validation to publishing fields in relation to each other
* Adds I18n support and includes examples on how to localise attributes and error messages
* Re-enables the migration generator in modern Rails applications
* Removes an old view partial generator (that used deprecated ERB syntax)
* Adds a sample Code of Conduct (that was generated using Bundler)

I happen to be the gem owner on RubyGems and would like to release a new version soon but first I’d like to get these merged in if possible please. We should also work out how to push tags etc to the repository. If Unboxed are not keen on maintaining the gem, I’m more than happy to take care of it.

I also wonder whether the email in the gem specification is obsolete or still a thing.

### CODE REVIEW

**Comment by h-lame** [comment]
Hey @liquid this mostly looks good.  We'll have a chat about maintenance and get back to you with further comments if we're still keen to maintain this, or we'll work out how to transfer ownership if we're not.

**Comment by liquid** [comment]
ping @ubxd

**Comment by h-lame** [comment]
Oops! I meant to reply last week @liquid sorry!  We don't really use this gem anymore, and it would appear don't have anyone remaining with creds to release it to rubygems anyway if we did.  We think therefore it might be easiest if we transferred the repo to you and you can maintain it.  What do you think?  I guess how it'll need to work is that you'll need to delete your fork (but keep your branches locally), then we can transfer ownership to you and you can then repush your branches.  How does that sound?

**Comment by liquid** [comment]
@h-lame ok cool. I'll ensure i have the local copy then give you a heads up. Thanks!

**Comment by liquid** [comment]
@h-lame could you please transfer the app to the @rewire organisation? Thanks.

**Comment by liquid** [comment]
(polite ping @h-lame)

**Comment by h-lame** [comment]
Oops.  Sorry!  Doing it now.

**Comment by h-lame** [comment]
Actually, no I'm not.  I'd need admin permissions on @rewire which I don't think you'd want to give me.  @liquid - I've added you to a team that has admin on this repo so you should be able to move it away now.  Let me know if that doesn't work, and we can try something else.

**Pull request merged**
